import { Hono } from "hono";
import { runPipeline } from "../lib/pipeline";
import { governancePassed, runGovernance } from "../lib/governance";
import { getJob, saveJob } from "../lib/store";
import { createZip } from "../lib/zip";
import type { Engine, Env, GenerateJob, GenerateRequest } from "../types";

export const generateRoute = new Hono<{ Bindings: Env }>();

function newId(): string {
  return crypto.randomUUID();
}

function titleForJob(idea: string): { title: string; tagline: string } {
  const clean = idea.trim();
  const short = clean.split(/[.!?]/)[0]?.slice(0, 40).trim();
  return {
    title: short && short.length > 3 ? toTitleCase(short) : "Neon Requiem",
    tagline: clean.slice(0, 140),
  };
}

function toTitleCase(s: string): string {
  return s
    .split(" ")
    .filter(Boolean)
    .slice(0, 4)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

generateRoute.post("/", async (c) => {
  const body = await c.req.json<GenerateRequest>().catch(() => null);
  if (!body || !body.idea || body.idea.trim().length < 5) {
    return c.json({ error: "Please describe your game idea in at least a few words." }, 400);
  }

  const stages = await runPipeline(body, c.env);
  const governance = runGovernance(stages, body.idea);
  const { title, tagline } = titleForJob(body.idea);

  const job: GenerateJob = {
    id: newId(),
    createdAt: Date.now(),
    request: body,
    title,
    tagline,
    stages,
    governance,
    governancePassed: governancePassed(governance),
  };

  await saveJob(c.env, job);

  return c.json({ jobId: job.id });
});

generateRoute.get("/:id", async (c) => {
  const job = await getJob(c.env, c.req.param("id"));
  if (!job) return c.json({ error: "Job not found" }, 404);
  return c.json(job);
});

generateRoute.get("/:id/package", async (c) => {
  const job = await getJob(c.env, c.req.param("id"));
  if (!job) return c.json({ error: "Job not found" }, 404);

  const engine = (c.req.query("engine") as Engine) ?? job.request.platform ?? "unity";

  const manifestFiles = job.stages.flatMap((s) => s.files);
  const readme =
    `# ${job.title}\n\nGenerated by AEGIS AI\n\n` +
    `Target engine: ${engine}\n` +
    `Governance: ${job.governancePassed ? "ALL CHECKS PASSED" : "REVIEW RECOMMENDED"}\n\n` +
    job.governance.map((g) => `- [${g.status.toUpperCase()}] ${g.title}: ${g.detail}`).join("\n") +
    "\n";

  const zipBytes = createZip([
    { name: "README.md", content: readme },
    ...manifestFiles.map((f) => ({ name: f.path, content: f.content })),
  ]);

  c.header("Content-Type", "application/zip");
  c.header(
    "Content-Disposition",
    `attachment; filename="${job.title.replace(/\s+/g, "_")}_${engine}_package.zip"`
  );
  return c.body(zipBytes as unknown as ArrayBuffer);
});
